clc, clear, close all
tic

spatialX = 513;
spatialY = 513;
staticCmd = "/home/igkiou/ercrdr_angletracingNEE/renderer/samples/renderer3d_sample_bin " +...
"stricts=true " + ...
"threads=-1 " + ...
"precision=4 " + ...
"printInputs=false " + ...
"outFilePrefix=delete " +...
"numPhotons=100000 " +...
"sigmaT=0 " +...
"albedo=0.9 " +...
"gVal=0 " +...
"speed_u=1500 " +...
"n_o=1.3333 " +...
"mode=0 " +...
"er_stepsize=1e-3 " + ... 
"directTol=1e-6 " + ... 
"rrWeight=.001 " + ... 
"projectorTexture=/home/igkiou/ercrdr_angletracingNEE/renderer/images/White.pfm " +...
"useDirect=true " +...
"useAngularSampling=true " + ...
"maxDepth=-1 " +...
"maxPathlength=100000 " +...
"pathLengthMin=0 " +...
"pathLengthMax=100000 " +...
"pathLengthBins=1 " +...
"mediumLx=-.015 " + ...
"mediumRx=.015 " + ...
"distribution=none " + ...
"gOrKappa=1 " + ...
"halfThetaLimit=0 " + ...
"emitter_size=0.0005 " + ... \
"emitter_distance=0 " + ...
"emitter_lens_focalLength=0.05 " + ...
"emitter_lens_aperture=.3 " + ...
"emitter_lens_active=false " + ...
"sensor_size=0.005 " + ...
"sensor_distance=0 " + ...
"sensor_lens_aperture=.3 " + ...
"sensor_lens_focalLength=.2 " + ...
"sensor_lens_active=false " + ...
"gap=0 " + ...
"printInputs=false ";
% 
% [searchN, V] = computePeakPhotonsPerVoltage(staticCmd, spatialX, spatialY, n_max_min, n_max_max, nSearches);
% 
% figure('units','normalized','outerposition',[0 0 1 1])
% plot(searchN, V, 'lineWidth', 3);
% ylabel('photons at center pixel');
% xlabel('n_{max}');
% set(gca, 'fontSize', 14);


          
n_max_min =0.00001;
n_max_max =0.00100;
nSearches = 100;
gVar = 10;

frequencies = (832-30:10:1010)*1e3;
% frequencies = (1300)*1e3;
ns = zeros(size(frequencies));

for i=1:length(ns)
    varCmd = staticCmd + " " + ...
        "f_u=" + num2str(frequencies(i)) + " ";
    [n, searchN, V, smoothV] = computeFocusVoltage(varCmd, spatialX, spatialY, n_max_min, n_max_max, nSearches, gVar);
    ns(i) = n;
end

figure('units','normalized','outerposition',[0 0 1 1])
plot(frequencies/1e3, ns, 'bo-', 'lineWidth', 3);
xlabel('Frequency (in KHz)');
ylabel('n_{max}');
set(gca, 'fontSize', 48);
axis tight;
saveas(gcf, 'TransducerLengthvsFrequencies.png');

toc