clc, clear, close all
tic

spatialX = 129;
spatialY = 129;
staticCmd = "/home/igkiou/ercrdr_angletracingNEE/renderer/samples/renderer3d_sample_bin " +...
"stricts=true " + ...
"threads=-1 " + ...
"precision=4 " + ...
"printInputs=false " + ...
"outFilePrefix=delete " +...
"numPhotons=100000 " +...
"sigmaT=0 " +...
"albedo=0.9 " +...
"gVal=0 " +...
"f_u=832000 " +...
"speed_u=1500 " +...
"n_o=1.3333 " +...
"mode=0 " +...
"er_stepsize=1e-3 " + ... 
"directTol=1e-6 " + ... 
"rrWeight=.001 " + ... 
"projectorTexture=/home/igkiou/ercrdr_angletracingNEE/renderer/images/White.pfm " +...
"useDirect=true " +...
"useAngularSampling=true " + ...
"maxDepth=-1 " +...
"maxPathlength=100000 " +...
"pathLengthMin=0 " +...
"pathLengthMax=100000 " +...
"pathLengthBins=1 " +...
"mediumLx=-.015 " + ...
"mediumRx=.015 " + ...
"distribution=none " + ...
"gOrKappa=1 " + ...
"halfThetaLimit=0 " + ...
"emitter_size=0.0005 " + ... \
"emitter_distance=0 " + ...
"emitter_lens_focalLength=0.05 " + ...
"emitter_lens_aperture=.3 " + ...
"emitter_lens_active=false " + ...
"sensor_size=0.005 " + ...
"sensor_distance=0 " + ...
"sensor_lens_aperture=.3 " + ...
"sensor_lens_focalLength=.2 " + ...
"sensor_lens_active=false " + ...
"gap=0 " + ...
"printInputs=false ";
% 
% [searchN, V] = computePeakPhotonsPerVoltage(staticCmd, spatialX, spatialY, n_max_min, n_max_max, nSearches);
% 
% figure('units','normalized','outerposition',[0 0 1 1])
% plot(searchN, V, 'lineWidth', 3);
% ylabel('photons at center pixel');
% xlabel('n_{max}');
% set(gca, 'fontSize', 14);


          
n_max_min =0.0001;
n_max_max =0.10;
nSearches = 1000;
gVar = 1;

[n, searchN, V, smoothV] = computeFocusVoltage(staticCmd, spatialX, spatialY, n_max_min, n_max_max, nSearches, gVar);
n

figure('units','normalized','outerposition',[0 0 1 1])
plot(searchN, V, 'lineWidth', 3, 'bo-', 'lineWidth', 3);
ylabel('photons at center pixel');
xlabel('n_{max}');
set(gca, 'fontSize', 48);
axis tight;
toc