clc, clear, close all
tic

spatialX = 1024;
spatialY = 1024;
staticCmd = "/home/igkiou/ercrdr_angletracingNEE/renderer/samples/renderer3d_sample_bin " +...
"stricts=true " + ...
"threads=-1 " + ...
"precision=4 " + ...
"printInputs=false " + ...
"outFilePrefix=delete " +...
"numPhotons=100000 " +...
"sigmaT=0 " +...
"albedo=0.9 " +...
"gVal=0 " +...
"f_u=832000 " +...
"speed_u=1500 " +...
"n_o=1.3333 " +...
"phi_min=1.5708 " +...
"phi_max=1.5708 " +...
"mode=0 " +...
"er_stepsize=1e-3 " + ... 
"directTol=1e-6 " + ... 
"rrWeight=.001 " + ... 
"projectorTexture=/home/igkiou/ercrdr_angletracingNEE/renderer/images/White.pfm " +...
"useDirect=true " +...
"useAngularSampling=true " + ...
"maxDepth=-1 " +...
"maxPathlength=100000 " +...
"pathLengthMin=0 " +...
"pathLengthMax=100000 " +...
"pathLengthBins=1 " +...
"mediumLx=-.015 " + ...
"mediumRx=.015 " + ...
"distribution=none " + ...
"gOrKappa=1 " + ...
"halfThetaLimit=0 " + ...
"emitter_size=0.01 " + ... \
"emitter_distance=0 " + ...
"emitter_lens_focalLength=0.05 " + ...
"emitter_lens_aperture=.3 " + ...
"emitter_lens_active=false " + ...
"sensor_size=0.01 " + ...
"sensor_distance=0 " + ...
"sensor_lens_aperture=.3 " + ...
"sensor_lens_focalLength=.2 " + ...
"sensor_lens_active=false " + ...
"gap=0 " + ...
"printInputs=false ";
% 
% [searchN, V] = computePeakPhotonsPerVoltage(staticCmd, spatialX, spatialY, n_max_min, n_max_max, nSearches);
% 
% figure('units','normalized','outerposition',[0 0 1 1])
% plot(searchN, V, 'lineWidth', 3);
% ylabel('photons at center pixel');
% xlabel('n_{max}');
% set(gca, 'fontSize', 14);

mode = 0;

modes = 0:8;
radius = containers.Map( modes, [0 38 93 123 158 192 225 256 289]);

staticCmd = staticCmd + "mode=" + string(mode) + " ";
          
n_max_min = 0.0001;
n_max_max = 0.0100;
nSearches = 100;
gVar = 5;

[n, searchN, V, smoothV, data] = computeFocusVoltage(staticCmd, spatialX, spatialY, n_max_min, n_max_max, nSearches, gVar, 513+radius(mode), 513);
n

% figure('units','normalized','outerposition',[0 0 1 1])
% plot(searchN, V', 'bo-', 'lineWidth', 3);
plot(searchN, smoothV', 'bo-', 'lineWidth', 3);
% ylabel('photons at center pixel');
% xlabel('n_{max}');
% set(gca, 'fontSize', 48);
% axis tight;
% saveas(gcf ,'VoltageVsPeak_277000.png');
toc